blank_issues_enabled: false
contact_links:
  - name: "Bug Report"
    url: "https://github.com/{owner}/{repo}/issues/new?template=bug_report.md"
  - name: "Feature Request"
    url: "https://github.com/{owner}/{repo}/issues/new?template=feature_request.md"
  
