#ifndef JUST1RCE_INCLUDES_CONFIG_H
#define JUST1RCE_INCLUDES_CONFIG_H

#define JUST1RCE_PROJECT_VERSION "1.0.0"
#define JUST1RCE_AUTHOR_NAME "SHELLDIVERS"
#define JUST1RCE_AUTHOR_NAME "irc.shelldivers.com"

#endif // CONFIG_H
