
// It is recommended to use std::setw(3) to ensure a three-character-wide output format.
// std::cout << std::setw(3) << std::setfill('0') << WELCOME << std::endl; 
#define	IRC_NOERROR 0
#define	RPL_WELCOME 1
#define	RPL_YOURHOST 2
#define	RPL_CHANNELMODEIS 324
#define	RPL_NOTOPIC 331
#define	RPL_TOPIC 332
#define	RPL_TOPICWHOTIME 333
#define	RPL_INVITING 341
#define	RPL_NAMREPLY 353
#define	RPL_ENDOFNAMES 366
#define	ERR_NOSUCHNICK 401
#define	ERR_NOSUCHCHANNEL 403
#define	ERR_CANNOTSENDTOCHAN 404
#define	ERR_TOOMANYCHANNELS 405
#define	ERR_NOORIGIN 409
#define	ERR_NORECIPIENT 411
#define	ERR_NOTEXTTOSEND 412
#define	ERR_NONICKNAMEGIVEN 431 
#define	ERR_ERRONEUSNICKNAME 432
#define	ERR_NICKNAMEINUSE 433
#define	ERR_USERNOTINCHANNEL 441
#define	ERR_NOTONCHANNEL 442
#define	ERR_USERONCHANNEL 443
#define	ERR_NOTREGISTERED 451
#define	ERR_NEEDMOREPARAMS 461
#define	ERR_ALREADYREGISTERED 462
#define	ERR_CHANNELISFULL 471
#define	ERR_INVITEONLYCHAN 473
#define	ERR_BADCHANNELKEY 475
#define	ERR_BADCHANMASK 476
#define	ERR_CHANOPRIVSNEEDED 482
