name: CMake Build

on:
  push: 
  pull_request:

jobs:
  CMakeBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up CMake
        uses: lukka/get-cmake@v3

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

