name: CMake Build

on:
  push: 
  pull_request:

jobs:
  Set_Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.30.0' 

  Configure_CMake:
    runs-on: ubuntu-latest
    needs: [Set_Environment]
    steps:
      - name: cmake build
        run: cmake --preset=default -S . -B build

  Run_Cppcheck:
    runs-on: ubuntu-latest
    needs: [Configure_CMake]
    steps:
      - name: CMake build and run cppcheck
        run: cmake --build build --target RunCppcheck

  Run_Cpplint:
    runs-on: ubuntu-latest
    needs: [Configure_CMake]
    steps:
      - name: CMake build and run cpplint
        run: cmake --build build --target RunCpplint

  Run_Google_Test:
    runs-on: ubuntu-latest
    needs: [Configure_CMake]
    steps:
      - name: CMake build and run google test
        run: cmake --build build --target RunGoogleTest



