name: cppCheck

on:
  [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Check for C++ files
        run: |
          if ls **/*.cpp **/*.hpp > /dev/null 2>&1; then
            echo "C++ files found. Proceeding with linting."
          else
            echo "No C++ files found. Skipping linting."
            exit 0
          fi

      - name: install cppcheck
        run: |
          sudo apt-get install -y cppcheck

      - name: install xmllint
        run: |
          sudo apt-get install -y libxml2-utils

      - name: make report.xml by cppcheck
        run: |
          cppcheck --enable=all --xml --output-file=report.xml .

      - name: remove inforamtion severity from report.xml
        run: |
          xmllint --xpath '//error[not(@severity="information")]' report.xml > filtered_report.xml

      - uses: Flast/cppcheck-sarif@v2
        with:
          input: report.xml
          output: report.sarif

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
          category: cppcheck