name: cppCheck

on:
  [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Check for C++ files
        run: |
          if ls **/*.cpp **/*.hpp > /dev/null 2>&1; then
            echo "EXIT_WORKFLOW=false" >> $GITHUB_ENV
          else
            echo "EXIT_WORKFLOW=true" >> $GITHUB_ENV
          fi

      - name: install cppcheck
        if: env.EXIT_WORKFLOW != true
        run: |
          sudo apt-get install -y cppcheck

      - name: install xmllint
        if: env.EXIT_WORKFLOW != true
        run: |
          sudo apt-get install -y libxml2-utils

      - name: make report.xml by cppcheck
        if: env.EXIT_WORKFLOW != true
        run: |
          cppcheck --enable=all --xml --output-file=report.xml .

      - name: remove inforamtion severity from report.xml
        if: env.EXIT_WORKFLOW != true
        run: |
          xmllint --xpath '//error[not(@severity="information")]' report.xml > filtered_report.xml

      - uses: Flast/cppcheck-sarif@v2
        if: env.EXIT_WORKFLOW != true\
        with:
          input: report.xml
          output: report.sarif

      - uses: github/codeql-action/upload-sarif@v3
        if: env.EXIT_WORKFLOW != true
        with:
          sarif_file: report.sarif
          category: cppcheck