name: cppCheck

on:
  [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: install cppcheck
        run: |
          sudo apt-get install -y cppcheck

      - name: install xmllint
        run: |
          sudo apt-get install -y libxml2-utils

      - name: Generate file list from only srcs and includes
        run: |
          find . -name "*.cc" -path "./srcs/**" -o -name "*.h" -path "./includes/**" > file_list.txt

      - name: make report.xml by cppcheck
        run: |
          if [ ! -s file_list.txt ]; then
            echo "No C++ files found."
            exit 0
          else
            xargs cppcheck --language=c++ --enable=all --suppress=missingInclude --xml --output-file=not_filtered_report.xml < file_list.txt
          fi

      - name: remove inforamtion severity from report.xml
        run: |
          xmllint --xpath '//error[@severity="warning" or @severity="error"]' not_filtered_report.xml > report.xml

      - uses: Flast/cppcheck-sarif@v2
        with:
          input: report.xml
          output: report.sarif

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
          category: cppcheck