name: C++ Linting

on:
  [push, pull_request]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install cpplint
        run: |
          pip install cpplint

      - name: For globstar  
        run: |
          shopt -s globstar

      - name: Generate file list
        run: |
          find . -name "*.cc" -o -name "*.h" > file_list.txt
          

      - name: Run cpplint
        run: |
          if [ ! -s file_list.txt ]; then
            echo "No C++ files found."
            exit 0
          else
            xargs cpplint < file_list.txt
          fi

